# Site settings
title: Deusmar Júnior
description: 'Web Developer'
url: ''
baseurl: '/'
google_analytics: 'UA-99017222-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Deusmar Júnior'
  email: deusmar.junior@hotmail.com
  twitter_username: deusmarjr
  facebook_username: deusmar.junior
  github_username:  deusmar
  linkedin_username:  deusmarjunior

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
